version: '3.1'
services:
  app:
    container_name: trillion_springboot
    image: trillion_springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - trillion_postgresql
  trillion_postgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb